// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuiorrwnzipvberuslas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1aW9ycnduemlwdmJlcnVzbGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MzU1NTcsImV4cCI6MjA2MDExMTU1N30.4VaSgNDSH59Fj-Px4xvbGmdyZqFVDA6DkdbfK2lt_Jc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);